### ISSUE TITLE
how is account recovery secure?

### ISSUE THREAD

**Issue by jkeesh** [dharma-eng/dharma-smart-wallet#2]
it seems there is an account recovery mechanism in the smart wallet - how is this secure? I see there is a 7 day time lock. however, who can initiate this? how is that controlled? who has access? It seems if there is a bug in this module it would compromise the whole thing.

**Comment by 0age** [comment]
Hi @jkeesh - you're correct that the [Account Recovery Manager](https://github.com/dharma-eng/dharma-smart-wallet/blob/master/contracts/account-recovery/DharmaAccountRecoveryManager.sol) has a seven-day timelock before account recovery is possible. Ownership of the account recovery manager is obviously very tightly controlled, and requires manual intervention from Dharma Labs. It would be really great to see someone put together an independent, third-party monitoring service that users could subscribe to for notifications on any relevant changes to this contract (or to the [Upgrade Beacon Controller Manager](https://github.com/dharma-eng/dharma-smart-wallet/blob/master/contracts/upgradeability/DharmaUpgradeBeaconControllerManager.sol)).

You'll also notice that there is a [`disableAccountRecovery`](https://github.com/dharma-eng/dharma-smart-wallet/blob/master/contracts/account-recovery/DharmaAccountRecoveryManager.sol#L168) function - if anyone feels fully confident in their own key management, or is _not_ fully confident in the account recovery mechanism, they can permanently and irrevocably "opt-out" (note that there is a three-day timelock for this operation).
